import { StudentAssignmentProps } from './professor-types';

const StudentsAssignmentData: StudentAssignmentProps[] = [
  {
    id: 1,
    name: 'Mohamed Ali Murad',
    missed: false,
    late: false,
    inTime: true,
    submissionTime: '10:00 AM',
  },
  {
    id: 2,
    name: 'Ali Ahmed',
    missed: true,
    late: false,
    inTime: false,
    submissionTime: null,
  },
  {
    id: 3,
    name: 'Ahmed Ali',
    missed: false,
    late: true,
    inTime: false,
    submissionTime: '12:45 PM',
  },
  {
    id: 4,
    name: 'Fatima Hassan',
    missed: false,
    late: false,
    inTime: true,
    submissionTime: '9:15 AM',
  },
  {
    id: 5,
    name: 'Omar Abdullah',
    missed: true,
    late: false,
    inTime: false,
    submissionTime: null,
  },
  {
    id: 6,
    name: 'Yara Mahmoud',
    missed: false,
    late: true,
    inTime: false,
    submissionTime: '10:20 AM',
  },
  {
    id: 7,
    name: 'Lina Salah',
    missed: true,
    late: false,
    inTime: false,
    submissionTime: null,
  },
  {
    id: 8,
    name: 'Karim Ali',
    missed: false,
    late: false,
    inTime: true,
    submissionTime: '8:30 AM',
  },
  {
    id: 9,
    name: 'Nadia Ahmed',
    missed: true,
    late: false,
    inTime: false,
    submissionTime: null,
  },
  {
    id: 10,
    name: 'Rana Samir',
    missed: false,
    late: true,
    inTime: false,
    submissionTime: '11:45 AM',
  },
  {
    id: 11,
    name: 'Ali Hassan',
    missed: true,
    late: false,
    inTime: false,
    submissionTime: null,
  },
  {
    id: 12,
    name: 'Sara Mohamed',
    missed: false,
    late: false,
    inTime: true,
    submissionTime: '10:10 AM',
  },
  {
    id: 13,
    name: 'Hassan Ali',
    missed: true,
    late: false,
    inTime: false,
    submissionTime: null,
  },
  {
    id: 14,
    name: 'Amira Mahmoud',
    missed: false,
    late: true,
    inTime: false,
    submissionTime: '9:40 AM',
  },
  {
    id: 15,
    name: 'Ahmed Ibrahim',
    missed: false,
    late: false,
    inTime: true,
    submissionTime: '8:00 AM',
  },
  {
    id: 16,
    name: 'Noura Hassan',
    missed: false,
    late: true,
    inTime: false,
    submissionTime: '11:20 AM',
  },
  {
    id: 17,
    name: 'Maha Ali',
    missed: true,
    late: false,
    inTime: false,
    submissionTime: null,
  },
  {
    id: 18,
    name: 'Youssef Ahmed',
    missed: false,
    late: false,
    inTime: true,
    submissionTime: '10:30 AM',
  },
  {
    id: 19,
    name: 'Hala Mohamed',
    missed: true,
    late: false,
    inTime: false,
    submissionTime: null,
  },
  {
    id: 20,
    name: 'Ragab Hassan',
    missed: false,
    late: false,
    inTime: true,
    submissionTime: '8:45 AM',
  },
  {
    id: 21,
    name: 'Nada Ali',
    missed: true,
    late: false,
    inTime: false,
    submissionTime: null,
  },
  {
    id: 22,
    name: 'Nour Ahmed',
    missed: false,
    late: true,
    inTime: false,
    submissionTime: '12:00 PM',
  },
  {
    id: 23,
    name: 'Mai Hassan',
    missed: false,
    late: false,
    inTime: true,
    submissionTime: '9:00 AM',
  },
  {
    id: 24,
    name: 'Ahmed Ali',
    missed: true,
    late: false,
    inTime: false,
    submissionTime: null,
  },
  {
    id: 25,
    name: 'Ali Ahmed',
    missed: false,
    late: true,
    inTime: false,
    submissionTime: '11:30 AM',
  }
];

export default StudentsAssignmentData;
